# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD$

PORTNAME=	devtools
PORTVERSION=	0.3
CATEGORIES=	base misc

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	Devtools Port

RUN_DEPENDS=	autoconf>=2.69:devel/autoconf \
 	        automake>=1.16.1:devel/automake \
		arc:devel/arcanist


USES=		metaport gettext gmake libtool
NO_ARCH=	yes


.include <bsd.port.mk>
