# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD$

PORTNAME=	miwidesktop
PORTVERSION=	0.1
CATEGORIES=	misc

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	Desktop Port

RUN_DEPENDS+=	xorg>0:x11/xorg \
		xfce4>0:x11-wm/xfce4 \
		rxvt>0:x11/rxvt-unicode \
		urxvt>0:x11/urxvt-perls \
		vim>0>:editors/vim \
		openssh-askpass>0:security/openssh-askpass \
		porttools>0:ports-mgmt/porttools \
		psearch>0:ports-mgmt/psearch \
		zsh>0:shell/zsh \
		git>0:devel/git \
		firfox>0:www/firefox \
		neomutt>0:mail/neomutt \
		chrome>0:www/chromium \
		bugzilla-cli>0:ports-mgmt/freebsd-bugzilla-cli

USES=		metaport
NO_ARCH=	yes



.include <bsd.port.mk>
