# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD$

PORTNAME=	miwidesktopmini
PORTVERSION=	0.3
CATEGORIES=	base misc

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	Desktop Port

RUN_DEPENDS+=	xorg>0:x11/xorg \
		awesome>0:x11-wm/awesome \
		urxvt:x11/rxvt-unicode \
		urxvt:x11/urxvt-perls \
		vim>0>:editors/vim \
		x11-ssh-askpass:security/openssh-askpass \
		porttools>0:ports-mgmt/porttools \
		psearch>0:ports-mgmt/psearch \
		zsh>0:shells/zsh \
		git>0:devel/git \
		firefox>0:www/firefox \
		neomutt>0:mail/neomutt \
		bz:ports-mgmt/freebsd-bugzilla-cli \
		mc>0:misc/mc  \
		subversion>0:devel/subversion \
		rsync:net/rsync \
		arandr:x11/arandr \
		python:lang/python \
		openvpn:security/openvpn \
		synergyc:sysutils/synergy \
		xorg>0:x11-drivers/xf86-video-intel \
		xorg>0:graphics/drm-next-kmod\
		slim:x11/slim
		

USES=		metaport
NO_ARCH=	yes


.include <bsd.port.mk>
